import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-restaurant-franchise-food-cost-rebate-recovery",
  "engine": "recovery",
  "title": "Restaurant Franchise Food-Cost Rebate Recovery",
  "shortTitle": "Restaurant Franchise Food-Cost Rebate Recovery",
  "tagline": "Capture food and packaging rebates earned across franchise purchasing volume and approved supplier programs.",
  "industry": "Restaurant Procurement Recovery",
  "buyer": "Restaurant franchisors and multi-unit operators",
  "uiPort": 4736,
  "apiPort": 5736,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Restaurant Franchise Food-Cost Rebate Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect supplier agreements, approved products, distributor purchases, store sales, volume tiers, marketing allowances, quality credits, rebate statements, and cash in one accountable workflow. Capture food and packaging rebates earned across franchise purchasing volume and approved supplier programs.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Restaurant Franchise Food-Cost Rebate Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("supplier-program-library","RFF01","Supplier program library","Execute supplier program library using supplier agreements, approved products, distributor purchases, store sales, volume tiers, marketing allowances, quality credits, rebate statements, and cash.","Produce a governed supplier program library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Franchise Network","text","Supplier / Franchise Network · Standard Case"],["caseReference","Supplier program library Reference","text","RFF01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1786250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2161363],["domainDriver","Rebate Type","select","Volume rebate",["Volume rebate","Marketing allowance","Quality credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Approved product registry case","Franchise location mapping case","Distributor purchase ingestion case","Net eligible volume case"]}),
feature("approved-product-registry","RFF02","Approved product registry","Execute approved product registry using supplier agreements, approved products, distributor purchases, store sales, volume tiers, marketing allowances, quality credits, rebate statements, and cash.","Produce a governed approved product registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Franchise Network","text","Supplier / Franchise Network · Standard Case"],["caseReference","Approved product registry Reference","text","RFF02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1786250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2161363],["domainDriver","Rebate Type","select","Volume rebate",["Volume rebate","Marketing allowance","Quality credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Approved product registry case","Franchise location mapping case","Distributor purchase ingestion case","Net eligible volume case"]}),
feature("franchise-location-mapping","RFF03","Franchise location mapping","Execute franchise location mapping using supplier agreements, approved products, distributor purchases, store sales, volume tiers, marketing allowances, quality credits, rebate statements, and cash.","Produce a governed franchise location mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Franchise Network","text","Supplier / Franchise Network · Standard Case"],["caseReference","Franchise location mapping Reference","text","RFF03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1786250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2161363],["domainDriver","Rebate Type","select","Volume rebate",["Volume rebate","Marketing allowance","Quality credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Approved product registry case","Franchise location mapping case","Distributor purchase ingestion case","Net eligible volume case"]}),
feature("distributor-purchase-ingestion","RFF04","Distributor purchase ingestion","Execute distributor purchase ingestion using supplier agreements, approved products, distributor purchases, store sales, volume tiers, marketing allowances, quality credits, rebate statements, and cash.","Produce a governed distributor purchase ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Franchise Network","text","Supplier / Franchise Network · Standard Case"],["caseReference","Distributor purchase ingestion Reference","text","RFF04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1786250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2161363],["domainDriver","Rebate Type","select","Volume rebate",["Volume rebate","Marketing allowance","Quality credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Approved product registry case","Franchise location mapping case","Distributor purchase ingestion case","Net eligible volume case"]}),
feature("net-eligible-volume","RFF05","Net eligible volume","Execute net eligible volume using supplier agreements, approved products, distributor purchases, store sales, volume tiers, marketing allowances, quality credits, rebate statements, and cash.","Produce a governed net eligible volume decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Franchise Network","text","Supplier / Franchise Network · Standard Case"],["caseReference","Net eligible volume Reference","text","RFF05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1786250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2161363],["domainDriver","Rebate Type","select","Volume rebate",["Volume rebate","Marketing allowance","Quality credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Approved product registry case","Franchise location mapping case","Distributor purchase ingestion case","Net eligible volume case"]}),
feature("volume-tier-calculation","RFF06","Volume tier calculation","Execute volume tier calculation using supplier agreements, approved products, distributor purchases, store sales, volume tiers, marketing allowances, quality credits, rebate statements, and cash.","Produce a governed volume tier calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Franchise Network","text","Supplier / Franchise Network · Standard Case"],["caseReference","Volume tier calculation Reference","text","RFF06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1786250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2161363],["domainDriver","Rebate Type","select","Volume rebate",["Volume rebate","Marketing allowance","Quality credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Approved product registry case","Franchise location mapping case","Distributor purchase ingestion case","Net eligible volume case"]}),
feature("growth-incentive","RFF07","Growth incentive","Execute growth incentive using supplier agreements, approved products, distributor purchases, store sales, volume tiers, marketing allowances, quality credits, rebate statements, and cash.","Produce a governed growth incentive decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Franchise Network","text","Supplier / Franchise Network · Standard Case"],["caseReference","Growth incentive Reference","text","RFF07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1786250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2161363],["domainDriver","Rebate Type","select","Volume rebate",["Volume rebate","Marketing allowance","Quality credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Approved product registry case","Franchise location mapping case","Distributor purchase ingestion case","Net eligible volume case"]}),
feature("marketing-allowance","RFF08","Marketing allowance","Execute marketing allowance using supplier agreements, approved products, distributor purchases, store sales, volume tiers, marketing allowances, quality credits, rebate statements, and cash.","Produce a governed marketing allowance decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Franchise Network","text","Supplier / Franchise Network · Standard Case"],["caseReference","Marketing allowance Reference","text","RFF08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1786250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2161363],["domainDriver","Rebate Type","select","Volume rebate",["Volume rebate","Marketing allowance","Quality credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Approved product registry case","Franchise location mapping case","Distributor purchase ingestion case","Net eligible volume case"]}),
feature("quality-shortfall-credit","RFF09","Quality shortfall credit","Execute quality shortfall credit using supplier agreements, approved products, distributor purchases, store sales, volume tiers, marketing allowances, quality credits, rebate statements, and cash.","Produce a governed quality shortfall credit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Franchise Network","text","Supplier / Franchise Network · Standard Case"],["caseReference","Quality shortfall credit Reference","text","RFF09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1786250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2161363],["domainDriver","Rebate Type","select","Volume rebate",["Volume rebate","Marketing allowance","Quality credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Approved product registry case","Franchise location mapping case","Distributor purchase ingestion case","Net eligible volume case"]}),
feature("return-spoilage-exclusion","RFF10","Return spoilage exclusion","Execute return spoilage exclusion using supplier agreements, approved products, distributor purchases, store sales, volume tiers, marketing allowances, quality credits, rebate statements, and cash.","Produce a governed return spoilage exclusion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Franchise Network","text","Supplier / Franchise Network · Standard Case"],["caseReference","Return spoilage exclusion Reference","text","RFF10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1786250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2161363],["domainDriver","Rebate Type","select","Volume rebate",["Volume rebate","Marketing allowance","Quality credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Approved product registry case","Franchise location mapping case","Distributor purchase ingestion case","Net eligible volume case"]}),
feature("rebate-accrual-ledger","RFF11","Rebate accrual ledger","Execute rebate accrual ledger using supplier agreements, approved products, distributor purchases, store sales, volume tiers, marketing allowances, quality credits, rebate statements, and cash.","Produce a governed rebate accrual ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Franchise Network","text","Supplier / Franchise Network · Standard Case"],["caseReference","Rebate accrual ledger Reference","text","RFF11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1786250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2161363],["domainDriver","Rebate Type","select","Volume rebate",["Volume rebate","Marketing allowance","Quality credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Approved product registry case","Franchise location mapping case","Distributor purchase ingestion case","Net eligible volume case"]}),
feature("supplier-statement-audit","RFF12","Supplier statement audit","Execute supplier statement audit using supplier agreements, approved products, distributor purchases, store sales, volume tiers, marketing allowances, quality credits, rebate statements, and cash.","Produce a governed supplier statement audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Franchise Network","text","Supplier / Franchise Network · Standard Case"],["caseReference","Supplier statement audit Reference","text","RFF12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1786250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2161363],["domainDriver","Rebate Type","select","Volume rebate",["Volume rebate","Marketing allowance","Quality credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Approved product registry case","Franchise location mapping case","Distributor purchase ingestion case","Net eligible volume case"]}),
feature("dispute-workflow","RFF13","Dispute workflow","Execute dispute workflow using supplier agreements, approved products, distributor purchases, store sales, volume tiers, marketing allowances, quality credits, rebate statements, and cash.","Produce a governed dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Franchise Network","text","Supplier / Franchise Network · Standard Case"],["caseReference","Dispute workflow Reference","text","RFF13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1786250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2161363],["domainDriver","Rebate Type","select","Volume rebate",["Volume rebate","Marketing allowance","Quality credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Approved product registry case","Franchise location mapping case","Distributor purchase ingestion case","Net eligible volume case"]}),
feature("cash-credit-reconciliation","RFF14","Cash credit reconciliation","Execute cash credit reconciliation using supplier agreements, approved products, distributor purchases, store sales, volume tiers, marketing allowances, quality credits, rebate statements, and cash.","Produce a governed cash credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Franchise Network","text","Supplier / Franchise Network · Standard Case"],["caseReference","Cash credit reconciliation Reference","text","RFF14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1786250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2161363],["domainDriver","Rebate Type","select","Volume rebate",["Volume rebate","Marketing allowance","Quality credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Approved product registry case","Franchise location mapping case","Distributor purchase ingestion case","Net eligible volume case"]}),
feature("brand-supplier-analytics","RFF15","Brand supplier analytics","Execute brand supplier analytics using supplier agreements, approved products, distributor purchases, store sales, volume tiers, marketing allowances, quality credits, rebate statements, and cash.","Produce a governed brand supplier analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Franchise Network","text","Supplier / Franchise Network · Standard Case"],["caseReference","Brand supplier analytics Reference","text","RFF15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1786250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2161363],["domainDriver","Rebate Type","select","Volume rebate",["Volume rebate","Marketing allowance","Quality credit"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Supplier program library case","Approved product registry case","Franchise location mapping case","Distributor purchase ingestion case","Net eligible volume case"]})
]);
